services:
  ollama:
    image: ollama/ollama:0.1.31
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
    ports:
      - "51434:11434"

  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "55432:5432"

  # web:
  #   build: .
  #   command: python app.py
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - d5432b
